config/routes.rb
Rails.application.routes.draw do

  resources :municipios_regiones
  resources :regiones
  resources :municipios
  
  root 'municipios#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/municipio.rb
class Municipio < ApplicationRecord

  has_many :municipios_regiones, dependent: :destroy
  has_many :regiones, through: :municipios_regiones

  validates :codigo, presence: true, uniqueness: true, numericality: { only_integer: true }

  after_update :eliminar_asociaciones

  def eliminar_asociaciones
    unless self.estado
      MunicipioRegion.where("municipio_id = ?", self.id).destroy_all
    end
  end

end

app/models/municipio_region.rb
class MunicipioRegion < ApplicationRecord

  belongs_to :municipio
  belongs_to :region
  
end

app/models/region.rb
class Region < ApplicationRecord

  has_many :municipios_regiones, dependent: :destroy
  has_many :municipios, through: :municipios_regiones

  validates :codigo, presence: true, uniqueness: true, numericality: { only_integer: true }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  before_action :set_municipio, only: [:show, :edit, :update, :destroy]

  # GET /municipios
  # GET /municipios.json
  def index
    @municipios = Municipio.all
  end

  # GET /municipios/1
  # GET /municipios/1.json
  def show
  end

  # GET /municipios/new
  def new
    @municipio = Municipio.new
  end

  # GET /municipios/1/edit
  def edit
  end

  # POST /municipios
  # POST /municipios.json
  def create
    @municipio = Municipio.new(municipio_params)

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to @municipio, notice: 'Municipio was successfully created.' }
        format.json { render :show, status: :created, location: @municipio }
      else
        format.html { render :new }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipios/1
  # PATCH/PUT /municipios/1.json
  def update
    respond_to do |format|
      if @municipio.update(municipio_params)
        format.html { redirect_to @municipio, notice: 'Municipio was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipio }
      else
        format.html { render :edit }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio.destroy
    respond_to do |format|
      format.html { redirect_to municipios_url, notice: 'Municipio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipio
      @municipio = Municipio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipio_params
      params.require(:municipio).permit(:codigo, :nombre, :estado)
    end
end

app/controllers/regiones_controller.rb
class RegionesController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regiones
  # GET /regiones.json
  def index
    @regiones = Region.all
  end

  # GET /regiones/1
  # GET /regiones/1.json
  def show
  end

  # GET /regiones/new
  def new
    @region = Region.new
  end

  # GET /regiones/1/edit
  def edit
  end

  # POST /regiones
  # POST /regiones.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regiones/1
  # PATCH/PUT /regiones/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regiones/1
  # DELETE /regiones/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regiones_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:codigo, :nombre, :municipio_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def hestado(v)
    if v
      "ACTIVO"
    else
      "INACTIVO"
    end
  end

end

app/views/layouts/_navegacion.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navegacion_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navegacion_links.html.erb
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Módulos <span class="caret"></span></a>
   <ul class="dropdown-menu">
     <li>
       <%= link_to 'Municipios', municipios_path %>
     </li>

     <li>
       <%= link_to 'Regiones', regiones_path %>
     </li>
   </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prueba" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Prueba" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navegacion' %>
    </header>

    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/municipios/_form.html.erb
<div class="containter">
  <%= simple_form_for(@municipio) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= f.input :codigo %>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= f.input :nombre %>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= f.input :estado, as: :select, collection: [["ACTIVO", true],["INACTIVO", false]], include_blank: false %>
    </div>


    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= f.button :submit, 'Guardar', class:'btn btn-success' %>
    </div>

  <% end %>
</div>

app/views/municipios/edit.html.erb
<h3>Editar Municipio</h3>

<%= render 'form', municipio: @municipio %>

app/views/municipios/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New", new_municipio_path, class: "btn btn-primary" %>
  </div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Codigo</th>
        <th>Nombre</th>
        <th>Estado</th>
        <th colspan="2">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @municipios.each do |municipio| %>
        <tr>
          <td><%= municipio.codigo %></td>
          <td><%= municipio.nombre %></td>
          <td><%= hestado(municipio.estado) %></td>
          <td><%= link_to "Editar", edit_municipio_path(municipio), class: "btn btn-default" %></td>
          <td><%= link_to 'Eliminar', municipio, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/municipios/new.html.erb
<h3>Registrar Municipio</h3>

<%= render 'form', municipio: @municipio %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código:</strong>
  <%= @municipio.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @municipio.nombre %>
</p>

<p>
  <strong>Estado:</strong>
  <%= hestado(@municipio.estado) %>
</p>

<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>

app/views/regiones/_form.html.erb
<div class="containter">
  <%= simple_form_for(@region) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <%= f.input :codigo %>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <%= f.input :nombre %>
    </div>


    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <ul style="list-style-type:none;">
        <strong></strong>
        <li><label> Municipios</label></li>
        <% Municipio.where("estado = ?", true).each do |municipio| %>

          <%= check_box_tag "region[municipio_ids][]", municipio.id, @region.municipios.include?(municipio) %>
          <%=h municipio.nombre %>

        <% end %>
      </ul>
    </div>


    <div class="col-md-12">
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <%= f.button :submit, 'Guardar', class:'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/regiones/edit.html.erb
<h3>Editar Región</h3>

<%= render 'form', region: @region %>

app/views/regiones/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New", new_region_path, class: "btn btn-primary" %>
  </div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Codigo</th>
        <th>Nombre</th>
        <th>Municipios</th>
        <th colspan="2">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @regiones.each do |region| %>
        <tr>
          <td><%= region.codigo %></td>
          <td><%= region.nombre %></td>
          <td><%= region.municipios.pluck(:nombre)*", " %></td>
          <td><%= link_to "Editar", edit_region_path(region), class: "btn btn-default" %></td>
          <td><%= link_to 'Eliminar', region, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/regiones/new.html.erb
<h3>Registrar Región</h3>

<%= render 'form', region: @region %>

app/views/regiones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código:</strong>
  <%= @region.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @region.nombre %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regiones_path %>